[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''
if args.key == '0' then args.key = 'o' end
'''
position = 'at'
payload = '''
if args.key == '0' and G.CONTROLLER.text_input_hook.config.ref_table and G.CONTROLLER.text_input_hook.config.ref_table.ref_value == "setup_seed" then args.key = 'o' end
'''
match_indent = true
